# Generated by Django 5.0.7 on 2024-07-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
