# Generated by Django 5.0.7 on 2024-08-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='repository_name',
        ),
    ]
