# Generated by Django 5.0.7 on 2024-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='display_name',
            field=models.CharField(max_length=512),
        ),
    ]
